### ISSUE TITLE
Don't allow `throw` statements.

### ISSUE THREAD

**Issue by rudolfbyker** [mdbetancourt/eslint-plugin-neverthrow#11]
In the spirit of `neverthrow`, we should not write `throw` statements.

Like these: https://github.com/eslint-functional/eslint-plugin-functional#no-exceptions (If you think we should use those, and not duplicate them here, that's also fine.)

**Comment by supermacro** [comment]
While I see it as a nice-to-have to have this rule baked into `eslint-plugin-neverthrow`, I don't think there's that much value given there's already an eslint rule for this as @rudolfbyker mentioned.

And yes, I still think `throw`ing has its place!
